# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a new network
#' @export
new_barry_graph <- function(n, source, target) {
    .Call(`_imaginarycss_new_barry_graph`, n, source, target)
}

#' @export
print.barry_graph <- function(x) {
    invisible(.Call(`_imaginarycss_print_barry_graph`, x))
}

#' @export
count_recip_errors <- function(x, n, end) {
    .Call(`_imaginarycss_count_recip_errors`, x, n, end)
}

