# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a new network
#' @export
new_barry_graph_cpp <- function(n, source, target, netsize, endpoints) {
    .Call(`_imaginarycss_new_barry_graph`, n, source, target, netsize, endpoints)
}

#' @export
print.barry_graph <- function(x) {
    invisible(.Call(`_imaginarycss_print_barry_graph`, x))
}

#' Add a counter for reciprocity errors
#' @param x An object of class [barry_graph].
#' @export
count_recip_errors <- function(x) {
    .Call(`_imaginarycss_count_recip_errors`, x)
}

