# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates a new network
#' @export
new_barry_graph_cpp <- function(n, source, target, netsize, endpoints) {
    .Call(`_imaginarycss_new_barry_graph`, n, source, target, netsize, endpoints)
}

#' @export
print.barry_graph <- function(x) {
    invisible(.Call(`_imaginarycss_print_barry_graph`, x))
}

#' Add a counter for reciprocity errors
#' @param x An object of class [barry_graph].
#' @export
count_recip_errors <- function(x) {
    .Call(`_imaginarycss_count_recip_errors`, x)
}

#' Computes census of imaginary errors
#' @param x An object of class [barry_graph].
#' @details
#' There are ten (10) values:
#' - (01) Accurate null
#' - (02) Partial false positive (null)
#' - (03) Complete false positive (null)
#' - (04) Partial false negative (assym)
#' - (05) Accurate assym
#' - (06) Mixed assym
#' - (07) Partial false positive (assym)
#' - (08) Complete false negative (full)
#' - (09) Partial false negative (full)
#' - (10) Accurate full
#' @export
count_imaginary_census <- function(x) {
    .Call(`_imaginarycss_count_imaginary_census`, x)
}

#' Retrieves the edgelist of a barry_graph
#' @param x An object of class barry_graph.
#' @return A matrix with two columns, the first one with the source and the
#'   second one with the target.
#' @export
barray_to_edgelist <- function(x) {
    .Call(`_imaginarycss_barray_to_edgelist`, x)
}

