---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# imaginarycss

<!-- badges: start -->
<!-- badges: end -->

The goal of imaginarycss is to ...

## Installation

You can install the released version of imaginarycss from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("imaginarycss")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("gvegayon/imaginary-structures")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(imaginarycss)

source_ <- c(1, 2, 3, 1) - 1
target_ <- c(2, 1, 4, 4) - 1

source_ <- c(source_, source_[-1] + 4)
target_ <- c(target_, target_[-1] + 4)

graph <- new_barry_graph(8, source_, target_)
graph

count_recip_errors(graph, 4, 8)
```

```{r example-krackhardt}
krack_data <- read.csv("data-raw/advice_nets.csv")
n          <- 21
end_points <- cumsum(rep(21, 22))[-1]

graph <- new_barry_graph(n*22, krack_data[,1] - 1, krack_data[,2] - 1)
ans   <- count_recip_errors(graph, 21, end_points)

ans$name <- gsub("[(][0-9]+[)]", "", ans$name)
ans
```

Now checking that none of these coincide completely

```{r}
tmp <- table(ans$value, ans$name)
tmp <- apply(tmp, 2, paste, collapse = "")
length(unique(tmp))  == 4 # Should be true
```

Checking out the distribution

```{r dist}
library(ggplot2)
ggplot(data = ans, aes(y = value)) +
  geom_histogram() + 
  facet_wrap(vars(name)) +
  coord_flip() +
  labs(title = "Distribution of type of errors")
```



