FROM rocker/tidyverse:4.5.1

# Adding R packages
RUN install2.r --error viridis tinytest reshape2

RUN install2.r --error languageserver quarto && \
  installGithub.r nx10/httpgd

RUN apt-get update && apt-get install --no-install-recommends -y valgrind gdb \
  libglpk-dev

CMD ["bash"]
